config/routes.rb
Bowling::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'login', :to => 'users/sessions#new', :as => :new_session
    get 'logout', :to => 'users/sessions#destroy', :as => :destroy_session
  end

  resources :leagues do
    get 'stats', on: :member
    get 'week/:week', on: :member, :action => 'week', :as => 'week'
  end

  resources :teams
  resources :bowlers
  resources :series do
    collection do
      get 'next_week'
    end
  end

  root :to => 'home#index'
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :teams
  has_many :series

  validates :name, presence: true
  validates :start_date, presence: true

  def day
    start_date.strftime('%A')
  end

  def to_s
    "#{name} - #{Date::MONTHNAMES[start_date.month]} #{start_date.year}"
  end

  def percentage_decimal
    percentage / 100.0
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
    respond_with(@leagues)
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    respond_with(@league)
  end

  # GET /leagues/new
  def new
    @league = League.new
    respond_with(@league)
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)
    @league.save
    respond_with(@league)
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    @league.update(league_params)
    respond_with(@league)
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_with(@league)
  end

  # GET /leagues/1/stats
  def stats
    @league = League.find(params[:id])
    @teams = @league.teams.includes([:bowlers, :league])
    weeks = []
    @league.series.select(:week).group(:week).order(:week).each do |series|
      weeks << series.week
    end
    @weeks = weeks
    @bowler_stats = @teams.map { |team| team.bowler_stats }.flatten.sort_by { |stat| stat[:handicap] }
  end

  # GET /leagues/1/week/2
  def week
    @week = params[:week]
    @series_by_team = []
    @games_by_team = []
    @totals_by_team = {}
    League.find(params[:id]).teams.each do |team|
      team_series = team.series.where(week: params[:week]).includes([:bowler, :scores]).order(:id)
      @series_by_team << team_series
      game1 = 0
      game2 = 0
      game3 = 0
      total = 0
      team_series.each do |series|
        game1 += series.scores[0].score
        game2 += series.scores[1].score
        game3 += series.scores[2].score
        total += series.total
      end
      totals = []
      totals << game1 << game2 << game3 << total
      @totals_by_team[team.id] = totals
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_league
    @league = League.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def league_params
    params.require(:league).permit(:name, :start_date, :weeks, :basis, :percentage)
  end
end

app/views/leagues/_form.html.erb
<%= bootstrap_form_for(league, style: :horizontal, left: "col-sm-2", right: "col-sm-4") do |f| %>
  <%= f.alert_message "Please fix the #{pluralize(league.errors.count, "error")} below." %>
  <%= f.text_field :name %>
  <%= f.text_field :start_date, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd'}, :append => raw('<i class="icon-calendar"></i>')  %>
  <%= f.number_field :weeks %>
  <%= f.number_field :basis %>
  <%= f.number_field :percentage, :append => '%' %>
  <%= f.form_group do %>
    <%= f.submit nil, :class => 'btn btn-primary'  %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
          leagues_path, :class => 'btn btn-default' %>
  <% end %>
<% end %>

app/views/leagues/edit.html.erb
<%- model_class = League -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', :league => @league %>

app/views/leagues/index.html.erb
<%- model_class = League -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:day) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:weeks) %></th>
      <th>Stats</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= link_to league.id, league_path(league) %></td>
        <td><%= league.name %></td>
        <td><%= league.day %></td>
        <td><%= league.start_date %></td>
        <td><%= league.weeks %></td>
        <td><%= link_to "Stats", stats_league_path(league) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_league_path(league), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      league_path(league),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_league_path,
            :class => 'btn btn-primary' %>

app/views/leagues/new.html.erb
<%- model_class = League -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', :league => @league %>

app/views/leagues/show.html.erb
<%- model_class = League -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @league.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:day) %>:</strong></dt>
  <dd><%= @league.day %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @league.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weeks) %>:</strong></dt>
  <dd><%= @league.weeks %></dd>
  <dt><strong>Handicap</strong></dt>
  <dd><%= "#{@league.percentage}% of #{@league.basis}" %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              leagues_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_league_path(@league), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              league_path(@league),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/leagues/stats.html.erb
<div class="page-header">
  <h1><%= @league.name %>  Stats</h1>
</div>

<%= line_chart @league.teams.map{|team|
  {:name => team.name, :data => team.series_scores} },
  {
    library: {
      yAxis: {
        min: nil
      }
    }
  }%>

<h3>Team Standings</h3>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Scratch Pins</th>
      <th>Scratch Game</th>
      <th>Scratch Series</th>
    </tr>
  </thead>
  <tbody>
  <% @teams.each do |team| %>
    <% team_stats = team.stats %>
    <% unless team_stats.nil? %>
    <tr>
      <td><%= team.name %></td>
      <td><%= team_stats[:scratch_pins] %></td>
      <td><%= team_stats[:high_game].total %></td>
      <td><%= team_stats[:high_series_pins] %></td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<h3>Player Standings</h3>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Handicap</th>
      <th>Average</th>
      <th>High Game</th>
      <th>High Series</th>
      <th>Scratch Game</th>
      <th>Scratch Series</th>
    </tr>
  </thead>
  <tbody>
  <% @bowler_stats.each do |bowler| %>
    <tr>
      <td><%= bowler[:name] %></td>
      <td><%= bowler[:handicap] %></td>
      <td><%= bowler[:average] %></td>
      <td></td>
      <td></td>
      <td><%= bowler[:scratch_game] %></td>
      <td><%= bowler[:scratch_series] %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<h3>Weekly Summaries</h3>
<% @weeks.each do |week| %>
    <p><%= link_to "Week #{week}", week_league_path(:id => @league, :week => week) %></p>
<% end %>

app/views/leagues/week.html.erb
<div class="page-header">
  <h1>Week <%= @week %> Stats</h1>
</div>

<% @series_by_team.each do |team_series| %>
  <% unless team_series.first.nil? %>
  <table class="table">
    <thead>
      <tr>
        <th>Bowler</th>
        <th>Handicap</th>
        <th>Game 1</th>
        <th>Game 2</th>
        <th>Game 3</th>
        <th>Series Average</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% team_series.includes(:team).each do |series| %>
        <tr>
          <td><%= series.bowler %></td>
          <td><%= series.handicap %>
          <% series.scores.each do |score| %>
            <td><%= score.score %></td>
          <% end %>
          <td><%= series.average %></td>
          <td><%= series.total %></td>
        </tr>
      <% end %>
      <tr>
        <td><b>Scratch Total</b></td>
        <td></td>
        <% team_totals = @totals_by_team[team_series.first.team.id] %>
        <% for i in 0..(team_totals.count - 2) %>
          <td><%= team_totals[i] %></td>
        <% end %>
        <td></td>
        <td><%= team_totals.last %></td>
      </tr>
      <% handicap = team_handicap team_series.first.team, @week.to_i %>
      <tr>
        <td><b>Handicap Total</b></td>
        <td><%= handicap %></td>
        <% for i in 0..(team_totals.count - 2) %>
          <td><%= team_totals[i] + handicap %></td>
        <% end %>
        <td></td>
        <td><%= team_totals.last + (handicap * (team_totals.count - 1)) %></td>
      </tr>
    </tbody>
  </table>
  <% end %>
<% end %>