config/routes.rb
Bowling::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'login', :to => 'users/sessions#new', :as => :new_session
    get 'logout', :to => 'users/sessions#destroy', :as => :destroy_session
  end

  resources :leagues do
    get 'stats', on: :member
    get 'week/:week', on: :member, :action => 'week', :as => 'week'
  end

  resources :teams
  resources :bowlers
  resources :series do
    collection do
      get 'next_week'
    end
  end

  root :to => 'home#index'
end

app/models/bowler.rb
class Bowler < ActiveRecord::Base
  has_and_belongs_to_many :teams

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  def short_name
    "#{first_name} #{last_name}"
  end

  def name
    if nickname.blank?
      short_name
    else
      "#{short_name} (#{nickname})"
    end
  end

  def to_s
    short_name
  end
end

app/controllers/bowlers_controller.rb
class BowlersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bowler, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /bowlers
  # GET /bowlers.json
  def index
    @bowlers = Bowler.all
    respond_with(@bowlers)
  end

  # GET /bowlers/1
  # GET /bowlers/1.json
  def show
    respond_with(@bowler)
  end

  # GET /bowlers/new
  def new
    @bowler = Bowler.new
    respond_with(@bowler)
  end

  # GET /bowlers/1/edit
  def edit
  end

  # POST /bowlers
  # POST /bowlers.json
  def create
    @bowler = Bowler.new(bowler_params)
    @bowler.save
    respond_with(@bowler)
  end

  # PATCH/PUT /bowlers/1
  # PATCH/PUT /bowlers/1.json
  def update
    @bowler.update(bowler_params)
    respond_with(@bowler)
  end

  # DELETE /bowlers/1
  # DELETE /bowlers/1.json
  def destroy
    @bowler.destroy
    respond_with(@bowler)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bowler
    @bowler = Bowler.includes(:teams => :league).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bowler_params
    params.require(:bowler).permit(:first_name, :last_name, :nickname, :email, :team_ids => [])
  end
end

app/views/bowlers/_form.html.erb
<%= bootstrap_form_for bowler, style: :horizontal, left: "col-sm-2", right: "col-sm-4" do |f| %>
  <%= f.alert_message "Please fix the #{pluralize(bowler.errors.count, "error")} below." %>
  <%= f.text_field :first_name, :class => 'form-control' %>
  <%= f.text_field :last_name, :class => 'form-control' %>
  <%= f.text_field :nickname, :class => 'form-control' %>
  <%= f.text_field :email, :class => 'form-control' %>
  <%= f.collection_check_boxes :team_ids, Team.all.includes(:league), :id, :to_s, {:label => 'Teams', :class => 'form-control'} %>
  <%= f.form_group do %>
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
          bowlers_path, :class => 'btn btn-default' %>
  <% end %>
<% end %>

app/views/bowlers/edit.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', :bowler => @bowler %>

app/views/bowlers/index.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bowlers.each do |bowler| %>
      <tr>
        <td><%= link_to bowler.id, bowler_path(bowler) %></td>
        <td><%= bowler.first_name %></td>
        <td><%= bowler.last_name %></td>
        <td><%= bowler.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bowler_path(bowler), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bowler_path(bowler),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bowler_path,
            :class => 'btn btn-primary' %>

app/views/bowlers/new.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render 'form', :bowler => @bowler %>

app/views/bowlers/show.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @bowler.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @bowler.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @bowler.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:teams) %>:</strong></dt>
  <dd>
    <ul style="padding-left:0;list-style:none;">
    <% @bowler.teams.each do |team| %>
      <li><%= team %></li>
    <% end %>
    </ul>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              bowlers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bowler_path(@bowler), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bowler_path(@bowler),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>