config/routes.rb
Bowling::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'login', :to => 'users/sessions#new', :as => :new_session
    get 'logout', :to => 'users/sessions#destroy', :as => :destroy_session
  end

  resources :leagues do
    get 'stats', on: :member
    get 'week/:week', on: :member, :action => 'week', :as => 'week'
  end

  resources :teams
  resources :bowlers
  resources :series do
    collection do
      get 'next_week'
    end
  end

  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bowling" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'bowling-ball.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Bowling</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%= menu_item "Leagues", leagues_path %>
            <%= menu_item "Teams", teams_path %>
            <%= menu_item "Bowlers", bowlers_path %>
            <%= menu_item "Series", series_index_path %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <%= menu_item "Logout", destroy_session_path %>
              </ul>
            </li>
            <li>
              <%= image_tag(current_user.picture, alt: "User Photo", class: 'nav-user-photo') %>
            </li>
          </ul>
          <% else %>
           <%= link_to image_tag('https://developers.google.com/accounts/images/sign-in-with-google.png', alt: 'Sign in with Google', class: 'gplus-login-button'), user_omniauth_authorize_path(:google_oauth2) %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Begin page content -->
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted">&copy; Jared Szechy 2014
        <% unless ENV["HEROKU_RELEASE_NAME"].nil? %>
          <small>
            <%= "#{ENV["HEROKU_RELEASE_NAME"]}-#{ENV["HEROKU_RELEASE_COMMIT"]}" %>
          </small>
        <% end %>
        </p>
      </div>
    </div>
  </body>
</html>